### ISSUE TITLE
don't show any account 

### ISSUE THREAD

**Issue by apt425410** [nichbar/share-vip#4]
i use vip youku but dont any account appear at command line

**Comment by apt425410** [comment]
![image](https://user-images.githubusercontent.com/27874509/46581499-0f7a1700-ca64-11e8-91b1-b2b36e907059.png)

**Comment by nichbar** [comment]
Really sorry to tell you that this CLI tool is unavailable for quite a long time.
I will add `deprecated` to the very top of this repo.
